apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  securityContext:
    runAsUser: 1000
  containers:
    - name: kubectl
      image: bitnami/kubectl
      command:
        - /bin/cat
      tty: true
    - name: git
      image: bitnami/git
      command:
        - /bin/cat
      tty: true
    - name: ssh-agent
      image: jenkins/ssh-agent
      command:
        - /bin/cat
      tty: true
    - name: kaniko
      image: registry.cn-chengdu.aliyuncs.com/eyecamera-in-staging/kaniko-project-executor:debug
      command:
        - /busybox/cat
      tty: true
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: kaniko-docker-secret
          mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-docker-secret
      secret:
        secretName: acr-push-credential
        items:
          - key: .dockerconfigjson
            path: config.json
